import { Geist, Geist_Mono } from "next/font/google";
import { ReduxProvider } from "@/store/reduxprovider";
import { auth } from "@/auth";
import "./globals.css";
import "@/lib/init-server";




import { Readex_Pro } from 'next/font/google';
const Readex_Pro_Font = Readex_Pro({ subsets: ['arabic'], weight: '400' });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "realestatesINsyria",
  description: "Generated by create next app",

};

export default async function RootLayout({ children }) {
  const session = await auth();
  console.log(session);
  return (
    <html lang="ar">
      <head>
        <meta charSet="UTF-8" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${Readex_Pro_Font.className}`}
      >

        <ReduxProvider session={session}>



          {children}

        </ReduxProvider>

      </body>
    </html>
  );
}
