import { Geist, Geist_Mono } from "next/font/google";
import { ReduxProvider } from "@/store/reduxprovider";
import { auth } from "@/auth";
import "./globals.css";
import "@/lib/init-server";




import { Readex_Pro } from 'next/font/google';
import NotificationsProvider from "@/components/notifications/notifications-provider";
import { AdminContextProvider } from "@/components/dashboard-components/listen";
const Readex_Pro_Font = Readex_Pro({ subsets: ['arabic'], weight: '400' });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "realestatesINsyria",
  description: "Generated by create next app",

};


export default async function RootLayout({ children }) {
  const session = await auth();
  const userId = session?.user?.id;

  return (
    <html lang="ar" dir="rtl">
      <head>
        <meta charSet="UTF-8" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${Readex_Pro_Font.className}`}
      >

        <ReduxProvider session={session}>
          <AdminContextProvider>
            <NotificationsProvider userId={userId}>
              {children}
            </NotificationsProvider>
          </AdminContextProvider>
          <div id="feedback_modal_root"></div>
          <div id="advanced_search_modal_root"></div>
          <div id="view_user_modal_root"></div>
          <div id="loading_modal"></div>
          <div id="confirm_delete_modal"></div>
          <div id="add_location_modal"></div>
        </ReduxProvider>

      </body>
    </html>
  );
}
